account/urls.py
from account import views
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

app_name = "account"

urlpatterns = [
    path('my_profile/', views.MyProfile.as_view(), name="my_profile"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('activate/<str:confirmation_token>', views.ActivateUserView.as_view(), name="activate"),
    path('password/', views.change_password, name='change_password'),
    path('logout', views.logout, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name="account/login.html", redirect_authenticated_user=True),
         name='login'),
    path('reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html",
                                                        email_template_name='account/password_reset_email.html',
                                                        subject_template_name='account/password_reset_subject.txt',
                                                        success_url=reverse_lazy('account:password_reset_done')),
         name='password_reset'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html",
                                                     success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html"),
         name='password_reset_complete'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),
         name='password_reset_done')
]

main/urls.py
"""Project urls."""
# from django.contrib import admin
# from django.conf.urls import url
from django.urls import path, include
from django.views.decorators import cache
from django.views.generic import TemplateView

from . import views
urlpatterns = [
    path('', views.index, name='homepage'),
    # path('', TemplateView.as_view(template_name='main/index.html'), name='homepage'),

    path('groups/new', views.group_create, name='group_create'),
    path('groups/<int:group_id>/', views.group_show, name='group_show'),
    path('groups/update/<int:post_id>/', views.group_update, name='group_update'),
    path('groups/list/', views.GroupsListView.as_view(), name='group_list'),

    path('groups/<int:group_id>/lectures/', views.lectures_show, name='lectures_show'),
    path('groups/<int:group_id>/tasks', views.tasks_show, name='tasks_show'),

    path('students/new', views.student_create, name='student_create'),
    # path('students/<int:group_id>/<int:student_id>', views.student_show, name='student_show'),

    path('lectures/list', views.LecturesGroupsListView.as_view(), name='lectures_list'),
    path('lectures/new', views.lecture_create, name='lecture_create'),


    path('tasks/list', views.TasksGroupsListView.as_view(), name='tasks_list'),
    path('tasks/new', views.task_create, name='task_create'),
    path('tasks/<int:task_id>', views.task_show, name='task_show'),

    # path('tasks/<int:task_id>/solution', views.new_solution, name='new_solution'),
    #
    # path('solutions/<int:solution_id>/result', views.solution_result, name='solution_result'),

    # path('literature/', views.literature, name='literature'),

    path('accounts/', include('django.contrib.auth.urls'), name='account'),
]

studying_assistant/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('account.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

main/models.py
from django.db import models

# Create your models here.


class Group(models.Model):
    """Group Model."""

    class Meta:
        """Group Model Meta."""

        db_table = "tb_groups"
        verbose_name_plural = "Групи"
        verbose_name = "Група"
    name = models.CharField("Назва групи", max_length=90)
    """Setup name and email fields types and lengths."""

    def __str__(self):
        """Print Author name."""
        return self.name


class Student(models.Model):
    """Student Model."""

    class Meta:
        """Student Model Meta."""

        db_table = "tb_students"
        verbose_name_plural = "Студенти"
        verbose_name = "Студент"
    name = models.CharField("Ім'я", max_length=30)
    surname = models.CharField("Прізвище", max_length=30, blank=True)
    grades_sum = models.IntegerField('Сума балів', default=0)
    email = models.EmailField("Пошта", max_length=80)
    group_id = models.ForeignKey("Group", on_delete=models.CASCADE, related_name='students')
    """Setup name and email fields types and lengths."""

    def __str__(self):
        """Print Student name."""
        return self.name

    def get_full_name(self):
        """Get Student Full Name."""
        return f'{self.name} {self.surname}'

    @property
    def full_name(self):
        """Print Student Full Name."""
        return f'{self.name} {self.surname}'


class Lecture(models.Model):
    """Material Model."""

    class Meta:
        """Material Model Meta."""

        db_table = "tb_lectures"
        verbose_name_plural = "Лекції"
        verbose_name = "Лекція"
    title = models.CharField("Тема лекції", max_length=90)
    description = models.TextField("Опис лекції", max_length=90)
    attachments = models.FileField('Матеріали', upload_to='../files/lectures/', blank=True)
    group_id = models.ForeignKey("Group", on_delete=models.CASCADE, related_name='lectures')
    """Setup name and email fields types and lengths."""

    def __str__(self):
        """Print Author name."""
        return self.title


class Task(models.Model):
    """Material Model."""

    class Meta:
        """Material Model Meta."""

        db_table = "tb_tasks"
        verbose_name_plural = "Задачі"
        verbose_name = "Задача"
    title = models.CharField("Назва задачі", max_length=90)
    description = models.TextField("Умова Задачі")
    testfile = models.FileField('Матеріали', upload_to='../files/tasks/', blank=True)

    group_id = models.ForeignKey("Group", on_delete=models.CASCADE, related_name='tasks')
    """Setup name and email fields types and lengths."""

    def __str__(self):
        """Print Author name."""
        return self.title


class Solution(models.Model):
    class Meta:
        """Material Model Meta."""

        db_table = "tb_solutions"
        verbose_name_plural = "Розв'язки"
        verbose_name = "Розв'язок"

    solution = models.FileField('Матеріали', upload_to='../files/tasks/', blank=True)

    task_id = models.ForeignKey("Task", on_delete=models.CASCADE, related_name='solutions')
    student_id = models.ForeignKey("Student", on_delete=models.CASCADE, related_name='solutions')

main/forms.py
from django import forms
from django.forms import ModelForm, Select, Textarea, TextInput, FileInput

from .models import Group, Student, Lecture, Task, Solution


class GroupForm(ModelForm):
    """Group Form."""

    class Meta:
        """Form Meta."""

        model = Group
        fields = ['name']
        widgets = {
            "name": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Назва групи"
            }),
        }


class StudentForm(ModelForm):
    """Subscriber Form."""

    group_id = forms.ModelChoiceField(
        queryset=Group.objects.all().order_by('name'),
        empty_label="Оберіть групу",
        widget=forms.Select(
            attrs={"class": "form-control"}
        )
    )

    class Meta:
        """Subscriber Form Meta."""

        model = Student
        fields = ['name', 'surname', 'email', 'group_id']
        widgets = {
            "name": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Ім'я"
            }
            ),
            "surname": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Прізвище"
            }
            ),
            "email": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Email студента "
            }
            ),
        }

    def save(self, commit=True):
        """Manual save method for Subscriber."""
        print("Subscriber before save")
        # form.ModelForm.save(self,commit)
        stud = super().save(commit=False)
        stud.email = stud.email.title()
        stud.save()
        return stud


class LectureForm(ModelForm):
    """Lecture Form."""

    group_id = forms.ModelChoiceField(
        queryset=Group.objects.all().order_by('name'),
        empty_label="Оберіть групу",
        widget=forms.Select(
            attrs={"class": "form-control"}
        )
    )

    class Meta:
        """Subscriber Form Meta."""

        model = Lecture
        fields = ['title', 'description', 'attachments', 'group_id']
        widgets = {
            "title": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Тема лекції"
            }
            ),
            "description": Textarea(attrs={
                "class": "form-control",
                "placeholder": "Опис лекції"
            }
            ),
            "attachments": FileInput(attrs={
                "class": "form-control",
                "placeholder": "Матеріали"
            }
            ),
        }


class TaskForm(ModelForm):
    group_id = forms.ModelChoiceField(
        queryset=Group.objects.all().order_by('name'),
        empty_label="Оберіть групу",
        widget=forms.Select(
            attrs={"class": "form-control"}
        )
    )

    class Meta:
        """Subscriber Form Meta."""

        model = Task
        fields = ['title', 'description', 'testfile', 'group_id']
        widgets = {
            "title": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Назва задачі"
            }
            ),
            "description": Textarea(attrs={
                "class": "form-control",
                "placeholder": "Умова задачі"
            }
            ),
            "testfile": FileInput(attrs={
                "class": "form-control",
                "placeholder": "Тестовий файл"
            }
            ),
        }


class SolutionForm:
    pass

main/views.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, DeleteView, ListView, View
from main.services.get_models import *
from main.models import Group, Student, Lecture, Task, Solution
from main.forms import GroupForm, StudentForm, LectureForm, TaskForm, SolutionForm

# Create your views here.


def index(request):
    return render(request, 'main/index.html', {'title': 'Домашня'})


def lectures(request):
    return render(request, 'main/lectures_list.html', {'title': 'Лекції'})


def tasks(request):
    return render(request, 'main/tasks.html', {'title': 'Задачі'})


def literature(request):
    return render(request, 'main/literature.html', {'title': 'Література'})


# ----- GROUPS -----


# def groups_all(request):
#     context = {'title': "Групи", "groups": group_all()}
#     return render(request, 'main/groups_all.html', context)


def group_update(request, group_id):
    """Update Posts."""
    err = ""
    pst = get_object_or_404(Group, pk=group_id)

    if request.method == "POST":
        form = GroupForm(instance=pst, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("group_list")
        else:
            err = "Не возможно обновить пост."
    else:
        form = GroupForm(instance=pst)
    context = {
        "form": form,
        "err": err
    }
    return render(request, "main/group_update.html", context=context)


def group_create(request):
    """Route Create Post."""
    errors = ''
    if request.method == "POST":
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("group_list")
        else:
            errors = "Не возможно сохранить пост."
    else:
        form = GroupForm()
    context = {"form": form, "errors": errors}
    return render(request, "main/group_create.html", context=context)


def group_show(request, group_id):
    """Route to Post by ID."""
    group = group_find(group_id)
    all_students = students_by_group(group_id)
    context = {
        "title": group.name,
        "students": all_students
    }
    return render(request, "main/group_show.html", context)


class GroupsListView(ListView):
    """Show list of posts analogously."""

    def get_queryset(self):
        """Set queryset to listview."""
        queryset = group_all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        """Set context data for ListView."""
        context = super().get_context_data(*args, **kwargs)
        context["cnt"] = context['object_list'].count()
        context["title"] = "Всі групи"
        return context


class DeleteGroupView(DeleteView):
    """Delete posts."""

    model = Group
    template_name = "main/group_delete.html"
    success_url = reverse_lazy("group_list")


# ----- STUDENTS -----


def student_create(request):
    errors = ''
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("group_list")
        else:
            errors = "Невозможно сохранить пост."
    else:
        form = StudentForm()
    context = {"form": form, "errors": errors}
    return render(request, "main/student_create.html", context=context)


# ----- LECTURES -----


class LecturesGroupsListView(ListView):
    """Show list of posts analogously."""
    template_name = 'main/lectures_list.html'

    def get_queryset(self):
        """Set queryset to listview."""
        queryset = group_all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        """Set context data for ListView."""
        context = super().get_context_data(*args, **kwargs)
        context["title"] = "Всі лекції"

        return context


def lectures_show(request, group_id):
    group = group_find(group_id)
    group_lectures = lectures_by_group(group_id)

    context = {
        "title": group.name,
        "lectures": group_lectures
    }

    return render(request, "main/lectures_show.html", context)


def lecture_create(request):
    errors = ''
    if request.method == "POST":
        form = LectureForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("lectures_list")
        else:
            errors = "Невозможно сохранить пост."
    else:
        form = LectureForm()
    context = {"form": form, "errors": errors}
    return render(request, "main/lecture_create.html", context=context)


# ----- LECTURES -----


class TasksGroupsListView(ListView):
    """Show list of posts analogously."""
    template_name = 'main/tasks_list.html'

    def get_queryset(self):
        """Set queryset to listview."""
        queryset = group_all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        """Set context data for ListView."""
        context = super().get_context_data(*args, **kwargs)
        context["title"] = "Всі задачі"

        return context


def tasks_show(request, group_id):
    group = group_find(group_id)
    group_tasks = tasks_by_group(group_id)

    context = {
        "title": group.name,
        "tasks": group_tasks
    }
    return render(request, "main/tasks_show.html", context)


def task_create(request):
    errors = ''
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("tasks_list")
        else:
            errors = "Невозможно сохранить пост."
    else:
        form = TaskForm()
    context = {"form": form, "errors": errors}
    return render(request, "main/task_create.html", context=context)


def task_show(request, task_id):
    task = task_find(task_id)

    context = {
        "title": task.title,
        "description": task.description,
        "testfile": task.testfile,
    }

    return render(request, "main/task_show.html", context)

main/templates/main/base.html
<!doctype html>
<html lang=" ">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/styles/main.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<nav class="nav justify-content-between bg-primary">
    <a class="p-3 text-white link-secondary" href="{% url "homepage" %}">Домашня</a>

    <a class="p-3 text-white link-secondary" href="{% url "group_list" %}">Список Груп</a>
{#    <a class="p-3 text-white link-secondary" href="{% url "groups_all" %}">Групи</a>#}
    <a class="p-3 text-white link-secondary" href="{% url "group_create" %}">Створити Групу</a>
    <a class="p-3 text-white link-secondary" href="{% url "lectures_list" %}">Лекції</a>
    <a class="p-3 text-white link-secondary" href="{% url "tasks_list" %}">Задачі</a>
{#    <a class="p-3 text-white link-secondary" href="{% url "literature" %}">Література</a>#}

{#    {% if request.user.is_authenticated %}#}
{#        <a class="nav-link" href="{% url "account:my_profile" %}">Аккаунт</a>#}
{#    {% else %}#}
{#        <a class="nav-link" href="{% url "account:my_profile" %}">Увійти</a>#}
{#        <a class="nav-link" href="{% url "account:my_profile" %}">Зареєструватись</a>#}
{#    {% endif %}#}

    <a class="p-3 text-white link-secondary" href="{% url "account:change_password" %}">Змінити пароль</a>
    <a class="p-3 text-white link-secondary" href="{% url "account:login" %}">Вхід</a>
    <a class="p-3 text-white link-secondary" href="{% url "account:signup" %}">Реєсрація</a>
    <a class="p-3 text-white link-secondary" href="{% url "account:logout" %}">Вийти</a>

</nav>
<div class="content">
    {% block content %}{% endblock %}
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main/templates/main/group_create.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block  content %}

    <div class="select2-container"></div>
        <h1>Посты</h1>
        <div class="error">
        {{ form.errors }}
        </div>

        <div class="payload">
            <form action="{% url "group_create" %}" method="post">
                {% csrf_token %}
                {{form.name}}
                <br><br>
                <button class="btn btn-success">Сохранить</button>
            </form>
        </div>

{% endblock %}

main/templates/main/group_delete.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block  content %}
    <div class="select2-container"></div>
        <h1>Удалить пост</h1>
    <h3>Удаление поста {{ group.name }}</h3>
        <div class="payload">
            <form method="post">
                {% csrf_token %}
                <strong>видалити групу?</strong>
                <br>
                <br>
                <button class="btn btn-danger">Удалить</button>
            </form>
        </div>

{% endblock %}

main/templates/main/group_show.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block  content %}
    {% load static %}
    <div class="select2-container"></div>
    <h1>Студенти групи {{ title }}</h1>
    <div class="payload">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col"><span style="color: black; ">ID</span></th>
                <th scope="col"><span style="color: black; ">Прізвище</span></th>
                <th scope="col"><span style="color: black; ">Ім'я</span></th>
                <th scope="col"><span style="color: black; ">Сума балів</span></th>
            </tr>
            </thead>
            <tbody>
            {% for student in students %}
            <tr>
                <th scope="row"><span style="color: #727272; ">{{ student.id }}</span></th>
                <th scope="row"><span style="color: #727272; ">{{ student.name }}</span></th>
                <th scope="row"><span style="color: #727272; ">{{ student.surname }}</span></th>
                <th scope="row"><span style="color: #727272; ">{{ student.grades_sum }}</span></th>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

main/templates/main/group_update.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block  content %}

    <div class="select2-container"></div>
        <h1>Обновить пост</h1>
        <div class="error">
        <h4 class="error">{{ err }}</h4>
            <div class="dj_error">
                {{ form.errors }}
            </div>


        </div>

        <div class="payload">

            <form method="post">
                {% csrf_token %}

                {{ form.title }}
                <br>
                {{ form.description }}
                <br>
                {{ form.content }}
                <br><br>

                <button class="btn btn-success">Сохранить</button>
            </form>
        </div>

{% endblock %}

main/templates/main/groups_all.html
{% extends "main/base.html" %}

{% block title %}Посты{% endblock %}
{% block  content %}
    <div class="select2-container"></div>
        <h1>{{ title }}</h1>
        <div class="payload">
            <ul>
                {% for group in groups %}
                    <div class="list-group">
                          <a href="{%  url "group_show" group_id=group.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
                          {{ group.name }}
                          </a>
                    </div>
                {% endfor %}
            </ul>
        </div>
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block title %}{% endblock %}
{% block  content %}
    <h1>Домашня</h1>
    <div class="container main-content"></div>
{% endblock %}

main/templates/main/lectures_list.html
{% extends 'main/base.html' %}

{% block title %}Posts{% endblock %}


{% block content %}
<div class="container">
    <h1>Лекції групи</h1>
    <div class="payload">
        <ul>
            <a href="{% url 'lecture_create' %}"><button class="btn btn-secondary">Нова лекція</button></a>
            <br><br>
            {% for group in group_list %}
            <h4 class="list-group-item list-group-item-action flex-column align-items-start">
                <a href="{% url 'lectures_show' group_id=group.id %}">{{ group.name }}</a>
            </h4>
            <hr>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

main/templates/main/literature.html
{% extends "main/base.html" %}

{% block title %}{% endblock %}
{% block  content %}
    <h1>Література</h1>
    <div class="container main-content"></div>
{% endblock %}

main/templates/main/student_create.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block  content %}

    <div class="select2-container"></div>
        <h1>Новий студент</h1>
        <div class="error">
        {{ form.errors }}
        </div>

        <div class="payload">
            <form action="{% url "student_create" %}" method="post">
                {% csrf_token %}
                {{form.name}}
                {{form.surname}}
                <br><br>
                {{form.email}}
                <br><br>
                {{form.group_id}}
                <br><br>
                <button class="btn btn-success">Сохранить</button>
            </form>
        </div>

{% endblock %}

main/templates/main/task_create.html
{% extends 'main/base.html' %}

{% block title %}Нова задача{% endblock %}


{% block content %}
<div class="container">
    <h1>{{ title }}</h1>

    <div class="error">
        {{ form.errors }}
    </div>
    <div class="payload">
        <form action="{% url "task_create" %}" method="post">
            {% csrf_token %}
            {{form.title}}
            {{form.description}}
            <br><br>
            {{form.testfile}}
            <br><br>
            {{form.group_id}}
            <br><br>
            <button class="btn btn-success">Створити завдання</button>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/tasks.html
{% extends "main/base.html" %}

{% block title %}{% endblock %}
{% block  content %}
    <h1>Задачі</h1>
    <div class="container main-content"></div>
{% endblock %}

main/templates/main/tasks_list.html
{% extends 'main/base.html' %}

{% block title %}Задачі{% endblock %}


{% block content %}
<div class="container">
    <h1>Задачі</h1>
    <div class="payload">
        <ul>
            <a href="{% url 'task_create' %}"><button class="btn btn-secondary">Нова Задача</button></a>
            <br><br>
            {% for group in group_list %}
            <h4 class="list-group-item list-group-item-action flex-column align-items-start">
                <a href="{% url 'tasks_show' group_id=group.id %}">{{ group.name }}</a>
            </h4>
            <hr>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

main/templates/main/tasks_show.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block  content %}
    {% load static %}
    <div class="select2-container"></div>
    <h1>Задачі групи {{ title }}</h1>
    <div class="payload">
        <ul>
            {% for task in tasks %}
                <div class="list-group-item list-group-item-action flex-column align-items-start">
                    <h4><a href="{% url 'task_show' task_id=task.id %}">{{ task.title }}</a></h4>
                    <p class="mb-1">{{task.description}}</p>
                </div>
            {% endfor %}
        </ul>
    </div>
{% endblock %}